version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_DB: ${PG_DATABASE:-financial}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./docker-data/mongo:/data/db
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./docker-data/redis:/data
